### ISSUE TITLE
KeyError: 'global_step'

### ISSUE THREAD

**Issue by saghiralfasly** [nickyisadog/latent-diffusion-inpainting#7]
Hi, thank you for making your code open. I just faced this error when I try running the training command: 

```CUDA_VISIBLE_DEVICES=0 python main.py --base ldm/models/ldm/inpainting_big/config.yaml --resume ldm/models/ldm/inpainting_big/last.ckpt --stage 1 -t --gpus 0,```

```Traceback (most recent call last):
  File "main.py", line 768, in <module>
    trainer.fit(model, data)
  File "/home/m288756/anaconda3/envs/sdm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File "/home/m288756/anaconda3/envs/sdm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 915, in _run
    self.checkpoint_connector.restore_training_state()
  File "/home/m288756/anaconda3/envs/sdm/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 164, in restore_training_state
    self.restore_loops()
  File "/home/m288756/anaconda3/envs/sdm/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 190, in restore_loops
    self.trainer.fit_loop.global_step = self._loaded_checkpoint["global_step"]
KeyError: 'global_step'```

wondering if you faced same problem.

**Comment by nickyisadog** [comment]
solved in https://github.com/nickyisadog/latent-diffusion-inpainting/issues/1
